- name: install maven
  ansible.builtin.dnf:
    name: maven
    state: present

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename shipping jar file
  ansible.builtin.command: mv target/{{ component }}-{{ version }}.jar {{ component }}.jar  
  args:
    chdir: /app